name: ğŸ¤– Dependencies Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Gum:
    runs-on: Ubuntu-Latest

    steps:
      - name: ğŸšš Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ€ Get the Latest Gum Version
        id: gum
        run: |
          tag="$(gh release list --repo='charmbracelet/gum' --limit=1 --json='name' --jq='.[].name')"
          echo "version=${tag:1}" | tee -a "$GITHUB_OUTPUT"

      - name: ğŸ“‹ Find and Replace the Gum Version
        id: find-replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "[0-9]+.[0-9]+.[0-9]+"
          replace: ${{ steps.gum.outputs.version }}
          include: "setup"

      - name: â¬†ï¸ Commit & Push Changes
        if: ${{ steps.find-replace.outputs.modifiedFiles > 0 }}
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            chore(setup): Version up Gum version

            Change Gum version to v${{ steps.gum.outputs.version }}.

  pre-commit:
    runs-on: Ubuntu-Latest

    steps:
      - name: ğŸšš Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ Setup Python
        uses: actions/setup-python@v5

      - name: ğŸš¸ Install pre-commit
        run: pip install pre-commit

      - name: ğŸš¸ Auto-update pre-commit.yml
        run: pre-commit autoupdate -c='data/pre-commit.yml'

      - name: ğŸ” Check the Changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.12

      - name: â¬†ï¸ Commit & Push Changes
        if: ${{ steps.changes.outputs.changed == 1 }}
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            chore(pre-commit): Update pre-commit tools

            To use the latest feature of pre-commit.
